version: "3"
services:
  api:
    image: pump_local
    container_name: pump_api
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=local
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
      - mongoclient
  mongo:
    image: mongo:latest
    container_name: pump_db
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
  mongoclient:
      image: mongoclient/mongoclient:latest
      container_name: mongoclient
      hostname: mongoclient
      environment:
        - MONGO_URL=mongodb://mongo:27017/pump
      volumes:
        - ./data/db:/data/db
      links:
        - mongo
      depends_on:
        - mongo
      ports:
        - "4000:3000"